# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea501cfccbe992923e1de3b0c4ae621d88b02d7f6e88711022b5204e29a3b94754392faec696220169c0f22e742618fe9fc7de26a409728230e7d119b87f1dc

test:
  secret_key_base: 89f151c7e6d39cd12494d2f9da475ce8e22193f8aaae1d8b1fdb43d7b392941a6d5e766b26ee0df303b10d8443f7e4f9723b7dfaed303345d5b955ae067d71fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0c6e8f3b3caab6f77c57ef745d0f7adbb4bb40498567eb72b9898eebd595f4fe9ccfb9548ca379058ba6048b6c7a10d8d41421bba6cd432e4dda5e091693d840
